### ISSUE TITLE
1.7.0 seems to be broken with hapi 10.5.0

### ISSUE THREAD

**Issue by slester** [lob/hapi-bookshelf-models#20]
Getting lots of errors like `Error: Cannot find module 'lib/models/userTeacherData'` after updating. I'll investigate more in the most recent commits to see what went wrong; I expect it's a glob/lookup problem.

Even changing my `options` to be in line with glob naming (an annoying unadvertised change that the README fails to implement, both methods should probably still work, i.e. specifying a directory or using glob notation) is having it break.

**Comment by slester** [comment]
I'll go ahead and ping @derbaeuerle since it was his code. Help! :)

**Comment by derbaeuerle** [comment]
Hey @slester,

Could you provide some more information about this issue please? It's hard to track down an error without stacktraces or a different project setup.

**Comment by jdmarshall** [comment]
I think I may be having the same issue.  It's hard to figure out the problem based on the stack trace, but this is what I got, and it looks like it's failing in register:

```
module.js:327
     throw err;
     ^

 Error: Cannot find module 'models/article'
     at Function.Module._resolveFilename (module.js:325:15)
     at Function.Module._load (module.js:276:25)
     at Module.require (module.js:353:17)
     at require (internal/module.js:12:17)
     at Object.exports.register (/root/api/node_modules/hapi-bookshelf-models/lib/index.js:67:11)
     at Object.target [as register] (/root/api/node_modules/hapi/node_modules/joi/lib/object.js:80:30)
     at each (/root/api/node_modules/hapi/lib/plugin.js:320:14)
     at iterate (/root/api/node_modules/hapi/node_modules/items/lib/index.js:36:13)
     at Object.exports.serial (/root/api/node_modules/hapi/node_modules/items/lib/index.js:39:9)
     at module.exports.internals.Plugin.internals.Plugin.register.each [as register] (/root/api/node_modules/hapi/lib/plugin.js:323:11)
     at Object.<anonymous> (/root/api/server.js:10:8)
     at Module._compile (module.js:397:26)
     at Object.Module._extensions..js (module.js:404:10)
     at Module.load (module.js:343:32)
     at Function.Module._load (module.js:300:12)
     at Function.Module.runMain (module.js:429:10)
     at startup (node.js:139:18)
     at node.js:999:3
```

**Comment by slester** [comment]
Yes, that's the same error stack I see. I'm using the typical `config` when loading the plugin as per the `README`: `models: "lib/models"` -- there's nothing "different" about it, and it worked with 1.6.0.

**Comment by jdmarshall** [comment]
@slester Did you find a workaround for this problem?  I've no idea how to get around this.

**Comment by jdmarshall** [comment]
@slester I'm using /models.  So you think that downgrading to 1.6.0 should get me back to work?

**Comment by derbaeuerle** [comment]
Hey @slester and @jdmarshall,

I'm sorry for the error within my code but I fixed it as fast as i could and created a new pull request. The error occurred due to the relative path configuration to the models directory. There are only absolute paths in the tests so the error wasn't thrown when executing them.

If you want to use the 1.7.0 version you could simply change your models attribute to an absolute path with `path.resolve` or wait until the pull request has been merged.

**Comment by jdmarshall** [comment]
No worries here.  I just started using your library so I was just happy to have a version running.  I'll probably wait until it 1.7.1.

**Comment by robinjoseph08** [comment]
This has been fixed with the help of @derbaeuerle and @slester and is now in version 1.7.1.

**Comment by jdmarshall** [comment]
I updated to 1.7.1 and this seems to be functioning now, thanks!
